name: deploy-tag-to-qa
on:
  workflow_dispatch:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - v1.*

jobs:
#  new_version:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#        with:
#          fetch-depth: 0
#      - name: Increment version
#        run: |
#          git config user.name "GitHub Actions"
#          git config user.email "actions@github.com"
#          yarn version --patch
#          git push
  update_qa:
#    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
#    needs: new_version
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'qa'
          fetch-depth: 0
      - name: 'push to qa'
        run: |
          git pull --all
          git merge origin/main --ff-only
          git push



