name: deploy-tag-to-qa
on:
  workflow_dispatch:

jobs:
  new_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Increment version
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          yarn version --patch
          git push

  update_qa:
    runs-on: ubuntu-latest
    needs: new_version
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'qa'
      - name: 'push to qa'
        run: |
          git pull --all
          git merge origin/main --ff-only
          git push



