name: deploy-tag-to-qa
on:
  workflow_dispatch:
#    inputs:
#      version:
#        description: 'Version number'
#        required: true
#        default: '1.1.1'


jobs:
  new_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Increment version
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          yarn config set version-git-tag true
          yarn config set version-commit-hooks true
          yarn version --patch
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'v$npm_package_version'
          tagging_message: 'v${{ env.VERSION }}'

  job2:
    runs-on: ubuntu-latest
    needs: new_version
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'qa'
      - name: 'push to qa'
        run: |
          git pull --all
          git merge origin/main --ff-only
      - uses: stefanzweifel/git-auto-commit-action@v4



