name: deploy-tag-to-qa
on:
  workflow_dispatch:
#    inputs:
#      version:
#        description: 'Version number'
#        required: true
#        default: '1.1.1'


jobs:
  new_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Increment version
        run: |
          yarn version --no-commit-hooks --no-git-tag-version --patch
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'v${{ env.VERSION }}'
          tagging_message: 'v${{ env.VERSION }}'

  job2:
    runs-on: ubuntu-latest
    needs: new_version
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'qa'
      - name: 'push to qa'
        run: |
          git reset dev --hard
