name: deploy-tag-to-qa
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'
        required: true
        default: '1.1.1'


jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: stefanzweifel/git-auto-commit-action@v4
      - name: Tag version
        run: |
          yarn version --new-version ${{ github.event.inputs.version }}
#  job2:
#    runs-on: ubuntu-latest
#    needs: job1
#    steps:
#      - run: echo ${{needs.job1.outputs.output1}}
