name: deploy-tag-to-qa
on:
  workflow_dispatch:
  push:
    # Pattern matched against refs/tags
    tags: ['v*']

jobs:
#  new_version:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#        with:
#          fetch-depth: 0
#      - name: Increment version
#        run: |
#          git config user.name "GitHub Actions"
#          git config user.email "actions@github.com"
#          yarn version --patch
#          git push
  update_qa:
#    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
#    needs: new_version
    env:
      GH_USERNAME: ${{ github.actor }}
      GH_ID: ${{ github.event.sender.id }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'qa'
          fetch-depth: 0
      - name: 'push to qa'
        run: |
          git pull --all
          git config user.name ${GH_USERNAME}
          git config user.email "${GH_ID}+${GH_USERNAME}@users.noreply.github.com"
          git merge origin/main --ff-only
          git push



