name: test mister launcher
on:
  workflow_dispatch:
#  push:
#    tags: [ 'v*' ]

jobs:
  update_qa:
    runs-on: ubuntu-latest
    env:
      GH_USERNAME: ${{ github.actor }}
      GH_ID: ${{ github.event.sender.id }}
    steps:
      - name: Who triggered the workflow
        run: |
          echo ${{ github.actor }}
          echo "${GH_ID}+${GH_USERNAME}@users.noreply.github.com"
          echo ${{ github.event.sender.id }}
        if: github.event_name == 'workflow_dispatch'


