name: test mister launcher
on:
  workflow_dispatch:
#  push:
#    tags: [ 'v*' ]

jobs:
  update_qa:
    runs-on: ubuntu-latest
    steps:
      - name: Who triggered the workflow
        run: |
          echo ${{ github.actor }}
          echo ${{ github.actor.toJSON() }}
          echo ${{ github.sender }}
          echo ${{ github.sender.toJSON() }}
        if: github.event_name == 'workflow_dispatch'



